// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lyzqgqhheosjthyoeeae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5enFncWhoZW9zanRoeW9lZWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDA5OTcsImV4cCI6MjA3MTk3Njk5N30.DzsSM0Al_o2cPCrsvzltFDdozZp-Kr-u2HlpUbDiOaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});